### ISSUE TITLE
data not in schema is valid

### ISSUE THREAD

**Issue by peter-mouland** [5alidz/tiny-schema-validator#2]
Thanks for the tool, I'm trying it out and can't see how to make the following fail/false

```js

import { createSchema, _ } from 'tiny-schema-validator';

export const schema = createSchema({
    metadata: _.record({
        vertical: _.record({
            id: _.string(),
            name: _.string(),
        }),
    }),
});

const json = {
 "metadata": { "vertical": { "id": "loans", "name": "Loans" } },
 "applyFeedback": {},
}

schema.is(json) // returns true

```

Is there anyway to make any addition/ undefined properties fail the schema validation?

**Comment by 5alidz** [comment]
Currently, both `is` and `produce` ignore additional properties. Just to not be annoying while doing something like data migration for example.

I was thinking of adding something like:

```js
schema.strictIs(data);
schema.strictProduce(data);
```

I'm going to push this later today.

**Comment by peter-mouland** [comment]
that would be epic 👍

**Comment by 5alidz** [comment]
I think it's just better to make it strict by default. thanks for the issue
